#!/bin/bash

[ "$1" ] || exit 1
[ -d "$1" ] || exit 1
[ -f "$1/spkgbuild" ] || exit 1

cat $1/spkgbuild \
| sed 's/# description\t: /# Description:\t/' \
| sed 's/# homepage\t: /# URL:\t\t/' \
| sed 's/# maintainer\t: .*/# Maintainer:\temmett1, emmett1 dot 2miligrams at gmail dot com/' \
| sed 's/# depends\t: /# Depends on:\t/' > $1/Pkgfile

rm $1/spkgbuild
cat $1/Pkgfile
