#!/bin/bash

[ "$1" ] || exit 1
[ -d "$1" ] || exit 1
[ -f "$1/Pkgfile" ] || exit 1

desc=$(grep "^# Description[[:blank:]]*:" $1/Pkgfile | sed 's/^# Description[[:blank:]]*:[[:blank:]]*//')
url=$(grep "^# URL[[:blank:]]*:" $1/Pkgfile | sed 's/^# URL[[:blank:]]*:[[:blank:]]*//')
maint="Emmett1, emmett1 dot 2miligrams at gmail dot com"
deps=$(grep "^# Depends on[[:blank:]]*:" $1/Pkgfile | sed 's/^# Depends on[[:blank:]]*:[[:blank:]]*//')

sed -e "s/# Description.*/# Description:\t$desc/" \
	-e "s/# URL.*/# URL:\t$url/" \
	-e "s/# Maintainer.*/# Maintainer:\t$maint/" \
	-e "s/# Depends on.*/# Depends on:\t$deps/" $1/Pkgfile
